In [2]:
import numpy as np

In [3]:
data = np.load('raw_data/_rawDecks_1_n=10000.npz')

In [4]:
print(data)
print(data.files)

NpzFile 'raw_data/_rawDecks_1_n=10000.npz' with keys: decks
['decks']


In [9]:
print(len(data['decks'][0]))
print(len(data['decks']))
print(data['decks'][0])

52
10000
[0 1 1 1 1 0 1 0 0 0 1 1 1 1 1 1 1 0 0 1 1 1 1 0 0 0 1 0 1 0 0 0 0 0 1 0 0
 0 1 0 1 1 0 0 1 1 1 1 0 0 0 0]


In [8]:
print(data['decks'].dtype)

uint8


In [10]:
data_scored = np.load('scored_data/_scoredDecks_195_n=10000.npy')

In [15]:
print(data_scored[0][0])

[[ 0  1  1  1  1  1  1  1]
 [-1  0 -1 -1  1 -1 -1 -1]
 [-1  1  0 -1  1 -1  1 -1]
 [-1  1  1  0  1 -1 -1 -1]
 [-1 -1 -1 -1  0 -1  1 -1]
 [-1  1  1  1  1  0  1 -1]
 [-1  1 -1  1 -1 -1  0 -1]
 [-1  1  1  1  1  1  1  0]]
